export default [
  { name: "Ruby", icon: "bi-gem", color: "crimson" },
  { name: "JavaScript", icon: "bi-filetype-js", color: "#cfb730" },
  { name: "JSON", icon: "bi-filetype-json", color: "#b9cf30" },
  { name: "TypeScript", icon: "bi-filetype-tsx", color: "#2991e6" },
  { name: "HTML", icon: "bi-filetype-html", color: "#db7f3d" },
  { name: "CSS", icon: "bi-filetype-css", color: "#307fcf" },
  { name: "SCSS", icon: "bi-filetype-scss", color: "#cf309a" },
  { name: "SASS", icon: "bi-filetype-sass", color: "#cf309a" },
  { name: "PHP", icon: "bi-filetype-php", color: "#7230cf" },
  { name: "Python", icon: "bi-filetype-py", color: "#cfb730" },
  { name: "Java", icon: "bi-filetype-java", color: "#6c30cf" },
  { name: "Shell", icon: "bi-filetype-sh", color: "#7d7d7d" },
  { name: "C", icon: "bi-filetype-cs", color: "#61c24e" },
  { name: "Objective-C", icon: "bi-filetype-cs", color: "#61c24e" },
  { name: "Vue", icon: "bi-file-earmark-code", color: "#2cc774" },
  { name: "React", icon: "bi-filetype-jsx", color: "#2cc7c7" },
  { name: "Go", icon: "bi-file-earmark-code", color: "#449db8" },
  { name: "_default", icon: "bi-file-earmark-code", color: "#90a38c" },
];
